#:kivy 2.1.0

#:include graph_panel/GraphPeer.kv
#:include data_entry_panel/DataEntryPeer.kv

<PurchasePeer>:

    BoxLayout:
        orientation: "horizontal"
        size: root.size
        spacing: 15
        padding: 15

        #Backdrop of the graph section of app
        GraphPeer:

        #Backdrop of the information entry section of app
        DataEntryPeer:
            size_hint_x: 0.4